### ISSUE TITLE
Question construct will not save if the Question has been selected first

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#796]
The Question has been selected (first), but it will not save and gives an error. 

(note I have not tried to save without the Question being selected) 
![image](https://user-images.githubusercontent.com/16664703/227235760-bd9076f5-d62e-4abd-b360-9c93f8a76ecb.png)

The error is not given if the Question is selected after the Type

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging

**Comment by HayleyMills** [comment]
Tested on the staging and I still get the error when I select the question first?

**Comment by simonreed** [comment]
@HayleyMills can you try again on staging please

**Comment by HayleyMills** [comment]
Tested on staging and this is no longer giving an error.
