### ISSUE TITLE
variables.txt is not loading

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#842]
This is on main and staging 

e.g. https://closer-archivist-staging.herokuapp.com/datasets/743/variables.txt?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6NjcsImFwaV9rZXkiOiJjNzlhODI4MzIxYTU3YWM4Njc0NSJ9.KKELJxMFNManETyxQdYVsRkPqZ2VpyuqbCylZ9LkN2Q

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging, and these pages are now loading.

**Comment by HayleyMills** [comment]
Reopening as I can no longer download variables.txt I logged out and in and it still doesn't work. This is on main e.g. https://closer-archivist.herokuapp.com/admin/datasets/1425/exports

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on production

**Comment by HayleyMills** [comment]
Tested on main and this is now working.
